# Generated by Django 6.0.2 on 2026-03-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='原名')),
                ('description', models.TextField(verbose_name='简介')),
                ('movie_type', models.CharField(choices=[('movie', '电影'), ('tv', '电视剧'), ('anime', '动漫')], default='movie', max_length=10)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='上映日期')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评分人数')),
                ('poster_url', models.URLField(blank=True, max_length=500, verbose_name='海报')),
                ('backdrop_url', models.URLField(blank=True, max_length=500, verbose_name='背景图')),
                ('trailer_url', models.URLField(blank=True, max_length=500, verbose_name='预告片')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='导演')),
                ('cast', models.JSONField(default=list, verbose_name='演员阵容')),
                ('play_links', models.JSONField(default=dict, verbose_name='播放链接')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-rating', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1, verbose_name='季数')),
                ('episode_number', models.IntegerField(verbose_name='集数')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长')),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='播出日期')),
                ('still_url', models.URLField(blank=True, max_length=500, verbose_name='剧照')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie')),
            ],
            options={
                'db_table': 'episodes',
                'ordering': ['season', 'episode_number'],
                'unique_together': {('movie', 'season', 'episode_number')},
            },
        ),
    ]
