# Generated by Django 6.0.2 on 2026-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='play_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='播放链接'),
        ),
    ]
